### ISSUE TITLE
PermissionError when passing path to init_chkpt config param

### ISSUE THREAD

**Issue by hieuchi911** [fostiropoulos/ablator#96]
## What happened:
- Run parallel experiment that initialize models from a checkpoint via `init_chkpt` config param
- Error message:
```
2023-07-14 14:11:16: Initializing model weights ONLY from checkpoint. \tmp\experiments_\experiment_7046_9991\0ee8_9991\best_checkpoints
Traceback (most recent call last):
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\test_init_chkpt.py", line 79, in <module>
    metrics = ablator.launch(working_directory = os.getcwd(), ray_head_address="auto")
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\ablator\main\mp.py", line 542, in launch
    self._init_state(
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\ablator\main\mp.py", line 410, in _init_state
    super()._init_state()
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\ablator\main\proto.py", line 62, in _init_state
    mock_wrapper._init_state(run_config=copy.deepcopy(self.run_config), debug=True)
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\ablator\main\model\main.py", line 548, in _init_state
    self._init_model_state(resume, smoke_test)
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\ablator\main\model\main.py", line 498, in _init_model_state
    self._load_model(self.current_checkpoint, model_only=True)
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\ablator\main\model\main.py", line 623, in _load_model
    save_dict = torch.load(checkpoint_path, map_location="cpu")
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork\venv\lib\site-packages\torch\serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork\venv\lib\site-packages\torch\serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork\venv\lib\site-packages\torch\serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: '\\tmp\\experiments_\\experiment_7046_9991\\0ee8_9991\\best_checkpoints'
```

## Version/ dependencies:
- python 3.10.6
- ray 2.2.0
- local OS: windows
- ray cluster also on local machine

## Reproduction script
test_init_chkpt.py
```python
from ablator import ModelConfig, OptimizerConfig, TrainConfig, RunConfig, ParallelConfig
from ablator import ModelWrapper, ParallelTrainer
from ablator.main.configs import SearchSpace

import torch
import torch.nn as nn

import shutil
import os

optimizer_config = OptimizerConfig(name="sgd", arguments={"lr": 0.1})

train_config = TrainConfig(
    dataset="test",
    batch_size=128,
    epochs=2,
    optimizer_config=optimizer_config,
    scheduler_config=None,
)

search_space = {
    "train_config.optimizer_config.arguments.lr": SearchSpace(
        value_range=[0, 10], value_type="int"
    ),
}

run_config = ParallelConfig(
    train_config=train_config,
    model_config=ModelConfig(),
    metrics_n_batches = 800,
    experiment_dir = "/tmp/experiments/",
    device="cuda",
    amp=True,
    random_seed = 42,
    total_trials = 5,
    concurrent_trials = 3,
    search_space = search_space,
    optim_metrics = {"val_loss": "min"},
    gpu_mb_per_experiment = 1024,
    cpus_per_experiment = 1,
    init_chkpt="<path-to-checkpoint>"
)

class MyCustomModel(nn.Module):
    def __init__(self, config: ModelConfig) -> None:
        super().__init__()
        self.lr = 0.01
        self.param = nn.Parameter(torch.ones(100))
        self.itr = 0

    def forward(self, x: torch.Tensor):
        x = self.param + torch.rand_like(self.param) * 0.01
        self.itr += 1
        if self.itr > 10 and self.lr > 5:
            raise Exception("large lr.")
        return {"preds": x}, x.sum().abs()

class TestWrapper(ModelWrapper):
    def make_dataloader_train(self, run_config: RunConfig):
        dl = [torch.rand(100) for i in range(100)]
        return dl

    def make_dataloader_val(self, run_config: RunConfig):
        dl = [torch.rand(100) for i in range(100)]
        return dl

if not os.path.exists(run_config.experiment_dir):
    shutil.os.mkdir(run_config.experiment_dir)

shutil.rmtree(run_config.experiment_dir)

wrapper = TestWrapper(MyCustomModel)

ablator = ParallelTrainer(
    wrapper=wrapper,
    run_config=run_config,
)

metrics = ablator.launch(working_directory = os.getcwd(), ray_head_address="auto")
```
To reproduce the error:
1. `ray start --head`
2. `python test_init_chkpt.py`

**Comment by hieuchi911** [comment]
Follow up question.
After updating init_chkpt parameter to point to an existing checkpoint file: `"/tmp/experiments1_/experiment_7046_9991/3e33_9991/best_checkpoints/MyEnsemble_0000000112.pt"`, 
I got another error AssertionError.
```
2023-07-14 15:03:05: Initializing model weights ONLY from checkpoint. \tmp\experiments1_\experiment_7046_9991\3e33_9991\best_checkpoints\MyEnsemble_0000000112.pt
Traceback (most recent call last):
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\test_init_chkpt.py", line 79, in <module>
    metrics = ablator.launch(working_directory = os.getcwd(), ray_head_address="auto")
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\ablator\main\mp.py", line 542, in launch
    self._init_state(
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\ablator\main\mp.py", line 410, in _init_state
    super()._init_state()
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\ablator\main\proto.py", line 62, in _init_state
    mock_wrapper._init_state(run_config=copy.deepcopy(self.run_config), debug=True)
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\ablator\main\model\main.py", line 548, in _init_state
    self._init_model_state(resume, smoke_test)
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\ablator\main\model\main.py", line 498, in _init_model_state
    self._load_model(self.current_checkpoint, model_only=True)
  File "C:\Users\hieuc\Documents\USC\Spring-2023\Research-Intern\ablator-fork-hieu\ablator\main\model\main.py", line 633, in _load_model
    assert run_config.uid == self.run_config.uid
AssertionError
```
It seems that in the checkpoint `run_config` object, the `optimizer_config` has `lr` value equals to a value that's sampled from SearchSpace in the range `[0,10]`, while for the constructed model, its optimizer config has `lr` value is `0.1` that's set in `optimizer_config` in the script above. This difference make the config uid to be different between the 2 config objects

## Reproduce the error
1. `ray start --head`
2. Run the code `python test_init_chkpt.py` without setting value for `init_chkpt` to create a checkpoint in experiment directory `/tmp/experiments/`
3. Store the checkpoint somewhere else that's not `/tmp/experiments/`
4. Update `init_chkpt` to the path to the checkpoint file and run code again `python test_init_chkpt.py`

**Comment by fostiropoulos** [comment]
The issue has been fixed in the latest version of ablator.
